spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.info.InfoEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.management.HeapDumpWebEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.env.EnvironmentEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.web.mappings.MappingsEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.sbom.SbomEndpointAutoConfiguration
  jmx:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        exclude: loggers, mappings, env, info, scheduledtasks, caches, sbom, heapdump, conditions
    jmx:
      exposure:
        exclude: "*"

logbook:
  format:
    style: json
