ansible_user: "ansible"
ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY') }}"

liquibase_username: "{{ lookup('env', 'DATABASE_LIQUIBASE_USERNAME') }}"
liquibase_password: "{{ lookup('env', 'DATABASE_LIQUIBASE_PASSWORD') }}"
liquibase_chdir: "{{ lookup('env', 'CI_PROJECT_DIR') }}/src/main/resources"
liquibase_rollback_tag: "{{ lookup('env', 'LIQUIBASE_ROLLBACK_TAG') | default('') }}"
liquibase_command: "{{ lookup('env', 'LIQUIBASE_COMMAND') | default('undefined', true) }}"

gitlab_registry_username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
gitlab_registry_token: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
gitlab_registry: "{{ lookup('env', 'CI_REGISTRY') }}"

dptb_root_dir: "opt"
dptb_main_dir: "dptb/{{ dptb_stand }}"
dptb_config_dir: "config"
dptb_name: "{{ lookup('env', 'SERVICE_NAME') | default('dptb', true) }}"
dptb_docker_web_port: "{{ lookup('env', 'DPTB_DOCKER_WEB_PORT') | default(8100, true) }}"
dptb_docker_actuator_port: "{{ lookup('env', 'DPTB_DOCKER_ACTUATOR_PORT') | default(7000, true) }}"
dptb_zone: "{{ lookup('env', 'DPTB_ZONE') }}"
dptb_image: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"
dptb_version: "{{ lookup('env', 'DPTB_VERSION') | default('unknown', true) }}"
dptb_telegram_bot_creator_id: "{{ lookup('env', 'TELEGRAM_BOT_CREATOR_ID') }}"
dptb_database_username:  "{{ lookup('env', 'DATABASE_SERVICE_USERNAME') }}"
dptb_database_password: "{{ lookup('env', 'DATABASE_SERVICE_PASSWORD') }}"
dptb_quite_mode_time_web_app_url: "{{ lookup('env', 'DPTB_QUITE_MODE_TIME_WEB_APP_URL') }}"
dptb_cors_allowed_origins: "{{ lookup('env', 'DPTB_CORS_ALLOWED_ORIGINS') | default('https://static.illine.ru', true)| split(',') }}"
