ansible_user: "ansible"
ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
ansible_port: "{{ lookup('env', 'ANSIBLE_PORT') }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY') }}"

liquibase_username: "{{ lookup('env', 'DATABASE_LIQUIBASE_USERNAME') }}"
liquibase_password: "{{ lookup('env', 'DATABASE_LIQUIBASE_PASSWORD') }}"
liquibase_chdir: "{{ lookup('env', 'CI_PROJECT_DIR') }}/src/main/resources"
liquibase_rollback_tag: "{{ lookup('env', 'LIQUIBASE_ROLLBACK_TAG') | default('') }}"
