liquibase_url: "{{ lookup('env', 'DATABASE_DPTB_TEST_URL') }}"

dptb_database_url: "{{ lookup('env', 'DATABASE_DPTB_TEST_URL') }}"
dptb_telegram_bot_token: "{{ lookup('env', 'TELEGRAM_BOT_TEST_TOKEN') }}"
dptb_stand: "test"
dptb_target_web_port: "{{ lookup('env', 'DPTB_DOCKER_WEB_TEST_PORT') | default(8100, true) }}"
dptb_target_actuator_port: "{{ lookup('env', 'DPTB_TARGET_ACTUATOR_TEST_PORT') | default(7100, true) }}"
dptb_quite_mode_time_web_app_url: "{{ lookup('env', 'DPTB_QUITE_MODE_TIME_WEB_APP_TEST_URL') }}"
