name: Mirror GitLab

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Push
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.5
        with:
          args: "https://gitlab.com/${{ secrets.GITLAB_USERNAME }}/${{ secrets.GITLAB_PROJECT }}"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "Illine"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID:  ${{ secrets.GITLAB_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}